# [[ranks]]
#   tier = 0
#   numAffixes = 0
#   defaultColor = "#FFFFFF"
#   weight = 60
#   growthFactor = 1
#   effects = []
#   presetAffixes = []
# [[ranks]]
#   tier = 1
#   numAffixes = 1
#   defaultColor = "#FFC0CB"
#   weight = 20
#   growthFactor = 1
#   effects = []
#   presetAffixes = []
# [[ranks]]
#   tier = 2
#   numAffixes = 2
#   defaultColor = "#FFFF00"
#   weight = 10
#   growthFactor = 4
#   effects = []
#   presetAffixes = []
# [[ranks]]
#   tier = 3
#   numAffixes = 3
#   defaultColor = "#FF9900"
#   weight = 5
#   growthFactor = 7
#   effects = []
#   presetAffixes = []
# [[ranks]]
#   tier = 4
#   numAffixes = 4
#   defaultColor = "#66FFFF"
#   weight = 3
#   growthFactor = 10
#   effects = []
#   presetAffixes = []
# [[ranks]]
#   tier = 5
#   numAffixes = 5
#   defaultColor = "#CC33FF"
#   weight = 2
#   growthFactor = 16
#   effects = []
#   presetAffixes = []


[[ranks]]
  tier = 0
  numAffixes = 0
  defaultColor = "#ffffff"
  weight = 40
  growthFactor = 0
  effects = []
  presetAffixes = []
[[ranks]]
  tier = 1
  numAffixes = 1
  defaultColor = "#ffff00"
  weight = 5
  growthFactor = 1
  effects = []
  presetAffixes = []
[[ranks]]
  tier = 2
  numAffixes = 2
  defaultColor = "#ff9900"
  weight = 20
  growthFactor = 4
  effects = []
  presetAffixes = []
[[ranks]]
  tier = 3
  numAffixes = 3
  defaultColor = "#66ffff"
  weight = 20
  growthFactor = 7
  effects = []
  presetAffixes = []
[[ranks]]
  tier = 4
  numAffixes = 4
  defaultColor = "#cc33ff"
  weight = 20
  growthFactor = 10
  effects = []
  presetAffixes = []
[[ranks]]
  tier = 5
  numAffixes = 5
  defaultColor = "#FF6600"
  weight = 20
  growthFactor = 13
  effects = []
  presetAffixes = []
[[ranks]]
  tier = 6
  numAffixes = 6
  defaultColor = "#FF0000"
  weight = 20
  growthFactor = 18
  effects = []
  presetAffixes = []
[[ranks]]
  tier = 7
  numAffixes = 7
  defaultColor = "#660000"
  weight = 20
  growthFactor = 18
  effects = []
  presetAffixes = []